# Site Settings
baseurl: "/yass-blog"
url : "https://yass-blog.github.io"

# Blog Settings
theme_settings :
  title : yass-blog
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : yasmine
    description : aspiring blue teamer and DFIR analyst. Here I write about security labs, capture-the-flag challenges, and everything I learn along the way.
    skills : 
      - skill : Python
        value : 75  # Percent value
      - skill : Linux / Bash 
        value : 70  # Percent value
      - skill : SQL
        value : 70  # Percent value
        
  # Icons
  icons :
    email: yasmine.mahfoudh@pm.me
    linkedin:  www.linkedin.com/in/yasmine-mahfoudh-/
    github: eth3ral0


  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
